channels:
  - defaults
  - conda-forge
  - bokeh
dependencies:
  - pandas
  - geojson
  - jupyterlab
  - jupyter
  - panel>=0.10
  - geoviews
  - iris
  - pyarrow
  - conda-tree
  - jupyter_contrib_nbextensions
  - nbdime
  - dagster
  - dagit
  - black
  - xlrd
  - pygal
  - cairosvg
  - hvplot
  - autoflake
  - isort
  - notebook
  - python
