version: "3"

services:
  django:
    build: ./django/
    ports:
      - "8000:8000"
    volumes:
      - ./django:/code
    command: python manage.py runserver 0.0.0.0:8000
  panel:
    build:
         context: ./panel 
         dockerfile: ./Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - ./panel:/code
      - ../data:/data
    environment:
    - PYTHONUNBUFFERED=1
    - PANEL_APP=./mednumapp.py 
    stdin_open: true
    tty: true
